### ISSUE TITLE
rbind of GOdata

### ISSUE THREAD

**Issue by TinclG** [TinclG/PAS_analysis#10]
when creating GOdata objects, i tried to merge them with rbind (as in vignette):

1.0_analysis/3.0 topGO
# Create topGOdata object
GOdataBP <- new("topGOdata",
    ontology = "BP", # use biological process ontology
    allGenes = geneList,
    geneSelectionFun = function(x)(x == 1),
  annot = annFUN.org, mapping = "org.Mm.eg.db", ID = "symbol")
GOdataCC <- new("topGOdata",
    ontology = "CC", # use biological process ontology
    allGenes = geneList,
    geneSelectionFun = function(x)(x == 1),
  annot = annFUN.org, mapping = "org.Mm.eg.db", ID = "symbol")
GOdataMF <- new("topGOdata",
        ontology = "MF", # use biological process ontology
        allGenes = geneList,
        geneSelectionFun = function(x)(x == 1),
    annot = annFUN.org, mapping = "org.Mm.eg.db", ID = "symbol")
**GOdata <- rbind(GOdataBP,GOdataCC,GOdataMF)**
_```
Error in rep(argl[[na]], length.out = nr) : 
  attempt to replicate an object of type 'S4'
```_

**Comment by vjmarteau** [comment]
I think you have human data right? ```mapping = "org.Mm.eg.db"```
